# Generated by Django 3.1.7 on 2021-04-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=100)),
                ('studentname', models.CharField(max_length=100)),
                ('standard', models.CharField(blank=True, default=12, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, default='English', max_length=100, null=True)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('status', models.CharField(default='Absent', max_length=100)),
            ],
        ),
    ]
