# Generated by Django 3.1.7 on 2021-04-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_studentattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
    ]
