# Generated by Django 3.1.7 on 2021-04-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_studentattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=100)),
                ('studentname', models.CharField(max_length=100)),
                ('standard', models.CharField(blank=True, default=12, max_length=100, null=True)),
                ('date', models.CharField(max_length=100)),
                ('applicationtype', models.CharField(max_length=100)),
                ('applicationdetail', models.CharField(max_length=100)),
                ('applicationstatus', models.CharField(default='unaccepted', max_length=100)),
            ],
        ),
    ]
